const mongoose = require('mongoose');
const dotenv = require('dotenv');

////sync 관련 !!또는 문법오류! console.log(x) <- x가 정의안됨
process.on('uncaughtException', err => {
  console.log('UNCAUGHT EXCEPTION! 💥 Shutting down...');
  console.log(err.name, err.message);
  process.exit(1);
});

//should be before const app + 한번만 쓰면 어디서든 process.env 접근가능
dotenv.config({ path: './config.env' }); //config 가 app 위에와야함
const app = require('./app');

const DB = process.env.DATABASE.replace(
  '<password>',
  process.env.DATABASE_PASSWORD
);

mongoose
  .connect(DB, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true
  })
  .then(() => console.log('DB connection successful!'));

const port = process.env.PORT || 4000;
const server = app.listen(port, () => {
  console.log(`App running on port ${port}...`);
});

//async 관련 !!, ex) DB 연결이 암호가 안맞아서 거절당했거나...
process.on('unhandledRejection', err => {
  console.log('UNHANDLED REJECTION! 💥 Shutting down...');
  console.log(err.name, err.message);
  server.close(() => {
    // 0성공 1실패
    process.exit(1);
  });
});

// heroku에서 갑자기 오류로인해 종료해야할때 이곳이 종료해주는곳임.. 위에 process.exit(1)은 아님!
process.on('SIGTERM', () => {
  console.log('👋 SIGTERM RECEIVED. Shutting down gracefully');
  server.close(() => {
    console.log('💥 Process terminated!');
  });
});
